version: '3.8'

services:
  # Blog Application
  blog_app:
    build: .
    container_name: blog_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on: []
    networks:
      - blog_network
    env_file:
      - ./.env.docker

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blog_app
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
